# Generated by Django 6.0.2 on 2026-02-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_forine', '0001_initial'),
        ('prestations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='SectionImage',
        ),
        migrations.RenameModel(
            old_name='PrestationFront',
            new_name='SectionPrestationFront',
        ),
    ]
