# Generated by Django 6.0.2 on 2026-02-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_forine', '0002_rename_image_sectionimage_and_more'),
        ('prestations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionPrestationFront',
            new_name='SectionPrestation',
        ),
    ]
