# Generated by Django 6.0.2 on 2026-02-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_forine', '0003_rename_sectionprestationfront_sectionprestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
