# Generated by Django 6.0.2 on 2026-02-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naiss',
            field=models.DateField(blank=True, null=True),
        ),
    ]
